import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Routes } from '@angular/router';

//import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { JSCComponent } from './jsc/jsc.component';
import { HomeComponent } from './home/home.component';
import { HtmlCComponent } from './html-c/html-c.component';

export const routes: Routes = [
  /*{
      path: '',
      redirectTo: '/auto-generated',
      pathMatch: 'full',
  },
  {
      path: 'auto-generated',
      component: AutoGeneratedComponent,
  },*/
  
  { path: '', redirectTo: '/home', pathMatch: 'full' },
  { path: 'JSC', component: JSCComponent },
  { path: 'home', component: HomeComponent },
  { path: 'html', component: HtmlCComponent }
];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
