import { BrowserModule } from '@angular/platform-browser';
import { NgModule, ErrorHandler } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { SideMenuComponent } from '@src/app/side-menu/side-menu.component';
import { JSCComponent } from '@src/app/jsc/jsc.component';
import { HomeComponent } from '@src/app/home/home.component';
import { HtmlCComponent } from '@src/app/html-c/html-c.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { ErrorHandlerService } from './services/error-handler.service';

@NgModule({
  declarations: [
    AppComponent,
    SideMenuComponent,
    JSCComponent,
    HomeComponent,
    HtmlCComponent,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule
  ],
  providers: [{
      provide: ErrorHandler,
      useClass: ErrorHandlerService,
    }],
  bootstrap: [AppComponent]
})
export class AppModule { }
