import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';

import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { SideMenuComponent } from '@src/app/side-menu/side-menu.component';
import { JSCComponent } from '@src/app/jsc/jsc.component';
import { HomeComponent } from '@src/app/home/home.component';
import { HtmlCComponent } from '@src/app/html-c/html-c.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';


// Uncomment and add to NgModule imports if you need to use two-way binding
// import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
// import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';

@NgModule({
  declarations: [
    AppComponent,
	  SideMenuComponent,
    JSCComponent,
    HomeComponent,
    HtmlCComponent,
    AutoGeneratedComponent
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
	  BrowserModule,
    FormsModule
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
